### PR TITLE
Simplified documentation for next warts remover version.

### PR DESCRIPTION
**Pull request by Jentsch**
Hi as soon as the change of puffnfresh/wartremover#245 is published the documentation could be simplified. This was the initial reason behind that pull request.

May, but not sure how, this could be predefined in [ScalaWarts.scala](https://github.com/danielnixon/playwarts/blob/master/sbt-plugin/src/main/scala/org/danielnixon/playwarts/PlayWarts.scala#L21)? But I'm not sure how to detect that the Routes plugin is enabled or not.

### CODE REVIEW

**Comment by Jentsch** [comment]
And I'm also not sure how to handle such (may be) long pending pull request. Sry

**Comment by danielnixon** [comment]
Thanks! Will sit on this until the next version of wartremover.

**Comment by Jentsch** [comment]
Thanks for doing so.
What about the idea to make this the default configuration?

**Comment by danielnixon** [comment]
Done in [04c3d62bbbe6d5b844f487bfa0f3e610b7431fac](https://github.com/danielnixon/playwarts/commit/04c3d62bbbe6d5b844f487bfa0f3e610b7431fac). I'll replace that with `routes.in(Compile).value` when wartremover is updated.

**Comment by Jentsch** [comment]
Nice! I wonder, if somebody disables the routes plugin in his/her project, would `routes.in(Compile).value` enable it again? And if so, how could this be prevented?

**Comment by danielnixon** [comment]
Good questions. I'm no sbt expert. I'll investigate.

**Pull request closed without merging**
